"""baseline schema

Revision ID: 20260428_01
Revises: 
Create Date: 2026-04-28 15:27:08.679627
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260428_01'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_invoice_configs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('invoice_title', sa.String(length=255), nullable=False),
    sa.Column('tax_number', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reimbursement_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('competition_name', sa.String(length=255), nullable=False),
    sa.Column('competition_location', sa.String(length=255), nullable=False),
    sa.Column('competition_start_date', sa.Date(), nullable=False),
    sa.Column('competition_end_date', sa.Date(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('member_ids', sa.JSON(), nullable=False),
    sa.Column('fee_categories', sa.JSON(), nullable=False),
    sa.Column('administrator_id', sa.String(length=128), nullable=False),
    sa.Column('project_info', sa.String(length=1024), nullable=False),
    sa.Column('reimburser_info', sa.String(length=1024), nullable=False),
    sa.Column('invoice_title', sa.String(length=255), nullable=False),
    sa.Column('tax_number', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reimbursement_tasks_administrator_id'), 'reimbursement_tasks', ['administrator_id'], unique=False)
    op.create_index(op.f('ix_reimbursement_tasks_status'), 'reimbursement_tasks', ['status'], unique=False)
    op.create_table('telegram_account_bindings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.String(length=128), nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_account_bindings_member_id'), 'telegram_account_bindings', ['member_id'], unique=True)
    op.create_index(op.f('ix_telegram_account_bindings_telegram_user_id'), 'telegram_account_bindings', ['telegram_user_id'], unique=True)
    op.create_table('user_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('member_code', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_accounts_actor_id'), 'user_accounts', ['actor_id'], unique=False)
    op.create_index(op.f('ix_user_accounts_role'), 'user_accounts', ['role'], unique=False)
    op.create_index(op.f('ix_user_accounts_username'), 'user_accounts', ['username'], unique=True)
    op.create_table('validation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_code', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_rule_code'), 'validation_results', ['rule_code'], unique=False)
    op.create_index('ix_validation_target', 'validation_results', ['target_type', 'target_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('automatic_reminder_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=128), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('deduplication_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['reimbursement_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automatic_reminder_task_created_at', 'automatic_reminder_tasks', ['task_id', 'created_at'], unique=False)
    op.create_index('ix_automatic_reminder_task_deduplication', 'automatic_reminder_tasks', ['task_id', 'deduplication_key'], unique=True)
    op.create_index('ix_automatic_reminder_task_member_kind', 'automatic_reminder_tasks', ['task_id', 'member_id', 'kind'], unique=False)
    op.create_index(op.f('ix_automatic_reminder_tasks_member_id'), 'automatic_reminder_tasks', ['member_id'], unique=False)
    op.create_index(op.f('ix_automatic_reminder_tasks_requested_by'), 'automatic_reminder_tasks', ['requested_by'], unique=False)
    op.create_index(op.f('ix_automatic_reminder_tasks_task_id'), 'automatic_reminder_tasks', ['task_id'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('failure_reason', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['reimbursement_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_export_job_task_created_at', 'export_jobs', ['task_id', 'created_at'], unique=False)
    op.create_index('ix_export_job_task_status', 'export_jobs', ['task_id', 'status'], unique=False)
    op.create_index(op.f('ix_export_jobs_requested_by'), 'export_jobs', ['requested_by'], unique=False)
    op.create_index(op.f('ix_export_jobs_status'), 'export_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_export_jobs_task_id'), 'export_jobs', ['task_id'], unique=False)
    op.create_table('material_reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('administrator_id', sa.String(length=128), nullable=False),
    sa.Column('member_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['reimbursement_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_material_reminder_task_created_at', 'material_reminders', ['task_id', 'created_at'], unique=False)
    op.create_index('ix_material_reminder_task_member', 'material_reminders', ['task_id', 'member_id'], unique=False)
    op.create_index(op.f('ix_material_reminders_administrator_id'), 'material_reminders', ['administrator_id'], unique=False)
    op.create_index(op.f('ix_material_reminders_member_id'), 'material_reminders', ['member_id'], unique=False)
    op.create_index(op.f('ix_material_reminders_task_id'), 'material_reminders', ['task_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('submitter_id', sa.String(length=128), nullable=True),
    sa.Column('task_id_hint', sa.String(length=36), nullable=True),
    sa.Column('submitter_id_hint', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('material_type', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('duplicate_of', sa.String(length=36), nullable=True),
    sa.Column('claimed_by', sa.String(length=128), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['reimbursement_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_material_task_sha256', 'materials', ['task_id', 'sha256'], unique=False)
    op.create_index(op.f('ix_materials_claimed_by'), 'materials', ['claimed_by'], unique=False)
    op.create_index(op.f('ix_materials_sha256'), 'materials', ['sha256'], unique=False)
    op.create_index(op.f('ix_materials_status'), 'materials', ['status'], unique=False)
    op.create_index(op.f('ix_materials_submitter_id'), 'materials', ['submitter_id'], unique=False)
    op.create_index(op.f('ix_materials_submitter_id_hint'), 'materials', ['submitter_id_hint'], unique=False)
    op.create_index(op.f('ix_materials_task_id'), 'materials', ['task_id'], unique=False)
    op.create_index(op.f('ix_materials_task_id_hint'), 'materials', ['task_id_hint'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=128), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('transaction_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('tax_number', sa.String(length=64), nullable=False),
    sa.Column('seller_name', sa.String(length=255), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('expense_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['reimbursement_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_task_number', 'invoices', ['task_id', 'invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_material_id'), 'invoices', ['material_id'], unique=False)
    op.create_index(op.f('ix_invoices_task_id'), 'invoices', ['task_id'], unique=False)
    op.create_table('recognition_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_final_fact', sa.Boolean(), nullable=False),
    sa.Column('failure_detail', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('recognized_fields', sa.JSON(), nullable=True),
    sa.Column('manual_corrections', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recognition_task_material', 'recognition_tasks', ['material_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_recognition_tasks_material_id'), 'recognition_tasks', ['material_id'], unique=False)
    op.create_index(op.f('ix_recognition_tasks_status'), 'recognition_tasks', ['status'], unique=False)
    op.create_table('expense_splits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=128), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expense_split_invoice_member', 'expense_splits', ['invoice_id', 'member_id'], unique=False)
    op.create_index(op.f('ix_expense_splits_invoice_id'), 'expense_splits', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_expense_splits_is_active'), 'expense_splits', ['is_active'], unique=False)
    op.create_index(op.f('ix_expense_splits_member_id'), 'expense_splits', ['member_id'], unique=False)
    op.create_table('invoice_supporting_material_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_supporting_material_link_material', 'invoice_supporting_material_links', ['material_id'], unique=False)
    op.create_index('ix_invoice_supporting_material_link_unique', 'invoice_supporting_material_links', ['invoice_id', 'material_id'], unique=True)
    op.create_index(op.f('ix_invoice_supporting_material_links_invoice_id'), 'invoice_supporting_material_links', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_supporting_material_links_material_id'), 'invoice_supporting_material_links', ['material_id'], unique=False)
    op.create_table('confirmations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('split_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=128), nullable=False),
    sa.Column('split_version', sa.Integer(), nullable=False),
    sa.Column('split_amount_cents', sa.Integer(), nullable=False),
    sa.Column('split_note', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dispute_reason', sa.String(length=1024), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['split_id'], ['expense_splits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_confirmation_split_member_version', 'confirmations', ['split_id', 'member_id', 'split_version'], unique=True)
    op.create_index(op.f('ix_confirmations_member_id'), 'confirmations', ['member_id'], unique=False)
    op.create_index(op.f('ix_confirmations_split_id'), 'confirmations', ['split_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirmations_split_id'), table_name='confirmations')
    op.drop_index(op.f('ix_confirmations_member_id'), table_name='confirmations')
    op.drop_index('ix_confirmation_split_member_version', table_name='confirmations')
    op.drop_table('confirmations')
    op.drop_index(op.f('ix_invoice_supporting_material_links_material_id'), table_name='invoice_supporting_material_links')
    op.drop_index(op.f('ix_invoice_supporting_material_links_invoice_id'), table_name='invoice_supporting_material_links')
    op.drop_index('ix_invoice_supporting_material_link_unique', table_name='invoice_supporting_material_links')
    op.drop_index('ix_invoice_supporting_material_link_material', table_name='invoice_supporting_material_links')
    op.drop_table('invoice_supporting_material_links')
    op.drop_index(op.f('ix_expense_splits_member_id'), table_name='expense_splits')
    op.drop_index(op.f('ix_expense_splits_is_active'), table_name='expense_splits')
    op.drop_index(op.f('ix_expense_splits_invoice_id'), table_name='expense_splits')
    op.drop_index('ix_expense_split_invoice_member', table_name='expense_splits')
    op.drop_table('expense_splits')
    op.drop_index(op.f('ix_recognition_tasks_status'), table_name='recognition_tasks')
    op.drop_index(op.f('ix_recognition_tasks_material_id'), table_name='recognition_tasks')
    op.drop_index('ix_recognition_task_material', table_name='recognition_tasks')
    op.drop_table('recognition_tasks')
    op.drop_index(op.f('ix_invoices_task_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_material_id'), table_name='invoices')
    op.drop_index('ix_invoice_task_number', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_materials_task_id_hint'), table_name='materials')
    op.drop_index(op.f('ix_materials_task_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_submitter_id_hint'), table_name='materials')
    op.drop_index(op.f('ix_materials_submitter_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_status'), table_name='materials')
    op.drop_index(op.f('ix_materials_sha256'), table_name='materials')
    op.drop_index(op.f('ix_materials_claimed_by'), table_name='materials')
    op.drop_index('ix_material_task_sha256', table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_material_reminders_task_id'), table_name='material_reminders')
    op.drop_index(op.f('ix_material_reminders_member_id'), table_name='material_reminders')
    op.drop_index(op.f('ix_material_reminders_administrator_id'), table_name='material_reminders')
    op.drop_index('ix_material_reminder_task_member', table_name='material_reminders')
    op.drop_index('ix_material_reminder_task_created_at', table_name='material_reminders')
    op.drop_table('material_reminders')
    op.drop_index(op.f('ix_export_jobs_task_id'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_status'), table_name='export_jobs')
    op.drop_index(op.f('ix_export_jobs_requested_by'), table_name='export_jobs')
    op.drop_index('ix_export_job_task_status', table_name='export_jobs')
    op.drop_index('ix_export_job_task_created_at', table_name='export_jobs')
    op.drop_table('export_jobs')
    op.drop_index(op.f('ix_automatic_reminder_tasks_task_id'), table_name='automatic_reminder_tasks')
    op.drop_index(op.f('ix_automatic_reminder_tasks_requested_by'), table_name='automatic_reminder_tasks')
    op.drop_index(op.f('ix_automatic_reminder_tasks_member_id'), table_name='automatic_reminder_tasks')
    op.drop_index('ix_automatic_reminder_task_member_kind', table_name='automatic_reminder_tasks')
    op.drop_index('ix_automatic_reminder_task_deduplication', table_name='automatic_reminder_tasks')
    op.drop_index('ix_automatic_reminder_task_created_at', table_name='automatic_reminder_tasks')
    op.drop_table('automatic_reminder_tasks')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_validation_target', table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_rule_code'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_user_accounts_username'), table_name='user_accounts')
    op.drop_index(op.f('ix_user_accounts_role'), table_name='user_accounts')
    op.drop_index(op.f('ix_user_accounts_actor_id'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_index(op.f('ix_telegram_account_bindings_telegram_user_id'), table_name='telegram_account_bindings')
    op.drop_index(op.f('ix_telegram_account_bindings_member_id'), table_name='telegram_account_bindings')
    op.drop_table('telegram_account_bindings')
    op.drop_index(op.f('ix_reimbursement_tasks_status'), table_name='reimbursement_tasks')
    op.drop_index(op.f('ix_reimbursement_tasks_administrator_id'), table_name='reimbursement_tasks')
    op.drop_table('reimbursement_tasks')
    op.drop_table('global_invoice_configs')
    # ### end Alembic commands ###
